services:
  network-deploy-services:
    networks:
      - eazybank

  microservice-db-service:
    extends:
      network-deploy-services
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      retries: 5
      interval: 10s
      timeout: 10s


  microservice-base-config:
    extends:
      service: network-deploy-services
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbit

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor